# Generated by Django 5.1.1 on 2024-10-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_article_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="image_url",
        ),
    ]
