# Generated by Django 5.1.3 on 2024-11-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cause_title", models.TextField()),
                ("social_cause_categories", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Figures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.TextField()),
                ("code", models.TextField()),
                ("categories", models.TextField(blank=True, null=True)),
                ("categories_tags", models.TextField(blank=True, null=True)),
                ("brands", models.TextField(blank=True, null=True)),
                ("brands_tags", models.TextField(blank=True, null=True)),
                ("origins", models.TextField(blank=True, null=True)),
                ("manufacturing_places", models.TextField(blank=True, null=True)),
                ("countries", models.TextField(blank=True, null=True)),
                (
                    "nutrition_grade_fr",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                ("main_category", models.TextField(blank=True, null=True)),
                ("ingredients_text", models.TextField(blank=True, null=True)),
                ("traces", models.TextField(blank=True, null=True)),
                ("energy_kcal_100g", models.IntegerField(blank=True, null=True)),
                ("proteins_100g", models.IntegerField(blank=True, null=True)),
                ("carbohydrates_100g", models.IntegerField(blank=True, null=True)),
                ("fat_100g", models.IntegerField(blank=True, null=True)),
                ("carbon_footprint_100g", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.TextField()),
                ("product_categories", models.TextField()),
                ("help_causes", models.ManyToManyField(to="project.cause")),
            ],
        ),
    ]
