# Generated by Django 5.1.3 on 2024-11-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="brands",
            field=models.TextField(blank=True, default="N/A", null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="brands_tags",
            field=models.TextField(blank=True, default="N/A", null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="carbohydrates_100g",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="carbon_footprint_100g",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.TextField(blank=True, default="N/A", null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="categories_tags",
            field=models.TextField(blank=True, default="N/A", null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="code",
            field=models.TextField(default="N/A"),
        ),
        migrations.AlterField(
            model_name="product",
            name="countries",
            field=models.TextField(blank=True, default="N/A", null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="energy_kcal_100g",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="fat_100g",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="ingredients_text",
            field=models.TextField(blank=True, default="N/A", null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="main_category",
            field=models.TextField(blank=True, default="N/A", null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="manufacturing_places",
            field=models.TextField(blank=True, default="N/A", null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="nutrition_grade_fr",
            field=models.CharField(blank=True, default="N/A", max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="origins",
            field=models.TextField(blank=True, default="N/A", null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.TextField(default="N/A"),
        ),
        migrations.AlterField(
            model_name="product",
            name="proteins_100g",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="traces",
            field=models.TextField(blank=True, default="N/A", null=True),
        ),
    ]
