# Generated by Django 5.1.3 on 2024-11-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_alter_product_brands_alter_product_brands_tags_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cause",
            name="cause_title",
        ),
        migrations.RemoveField(
            model_name="cause",
            name="social_cause_categories",
        ),
        migrations.AddField(
            model_name="cause",
            name="category",
            field=models.CharField(
                choices=[
                    ("Environmental Impact", "Environmental Impact"),
                    ("Labor Practices", "Labor Practices"),
                    ("Animal Welfare", "Animal Welfare"),
                    ("Health & Nutrition", "Health & Nutrition"),
                    ("Ethical Marketing", "Ethical Marketing"),
                    ("Community Support", "Community Support"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cause",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cause",
            name="title",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="ecoscore_grade",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="epi_score",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="packaging",
            field=models.TextField(blank=True, default="N/A", null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="production_system",
            field=models.TextField(blank=True, default="N/A", null=True),
        ),
    ]
