# Generated by Django 5.1.3 on 2024-11-18 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_remove_cause_cause_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnvironmentalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "carbon_footprint_100g",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "ecoscore_grade",
                    models.TextField(blank=True, default="N/A", null=True),
                ),
                ("packaging", models.TextField(blank=True, default="N/A", null=True)),
                (
                    "production_system",
                    models.TextField(blank=True, default="N/A", null=True),
                ),
                ("epi_score", models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="NutritionalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "energy_kcal_100g",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "proteins_100g",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "carbohydrates_100g",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("fat_100g", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "nutrition_grade_fr",
                    models.CharField(
                        blank=True, default="N/A", max_length=3, null=True
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Figures",
        ),
        migrations.RemoveField(
            model_name="product",
            name="carbohydrates_100g",
        ),
        migrations.RemoveField(
            model_name="product",
            name="carbon_footprint_100g",
        ),
        migrations.RemoveField(
            model_name="product",
            name="ecoscore_grade",
        ),
        migrations.RemoveField(
            model_name="product",
            name="energy_kcal_100g",
        ),
        migrations.RemoveField(
            model_name="product",
            name="epi_score",
        ),
        migrations.RemoveField(
            model_name="product",
            name="fat_100g",
        ),
        migrations.RemoveField(
            model_name="product",
            name="nutrition_grade_fr",
        ),
        migrations.RemoveField(
            model_name="product",
            name="packaging",
        ),
        migrations.RemoveField(
            model_name="product",
            name="production_system",
        ),
        migrations.RemoveField(
            model_name="product",
            name="proteins_100g",
        ),
        migrations.AddField(
            model_name="product",
            name="environmental_info",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="project.environmentalinfo",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="nutritional_info",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="project.nutritionalinfo",
            ),
        ),
    ]
