# Generated by Django 5.1.3 on 2024-11-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_environmentalinfo_nutritionalinfo_delete_figures_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="causes",
            field=models.ManyToManyField(blank=True, to="project.cause"),
        ),
    ]
