# Generated by Django 5.1.3 on 2024-11-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0009_alter_brand_brand_name_alter_brand_help_causes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cause",
            name="category",
            field=models.CharField(
                choices=[
                    ("Environmental Impact", "Environmental Impact"),
                    ("Labor Practices", "Labor Practices"),
                    ("Animal Welfare", "Animal Welfare"),
                    ("Health & Nutrition", "Health & Nutrition"),
                    ("Ethical Marketing", "Ethical Marketing"),
                ],
                max_length=50,
            ),
        ),
    ]
