# Generated by Django 5.1.2 on 2024-10-19 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_fb", "0004_remove_profile_image_file_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="profile",
            new_name="message",
        ),
        migrations.AddField(
            model_name="statusmessage",
            name="message_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mini_fb.image",
            ),
        ),
    ]
